name: Build Release

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build apk
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease

      - name: Sign artifact
        id: signArtifact
        uses: Tlaster/android-sign@v1.2.2
        with:
          releaseDirectory: app/build/outputs/apk/release
          output: build/release/signed
          alias: ${{ secrets.KEYALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: 30.0.3

      - name: List files
        run: ls build/release/signed

      - name: Upload apk
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Release artifact
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload Assets
        id: upload_assets
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest-release
          prerelease: false
          title: Release Build
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/output-metadata.json