name: Create Pull Request

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: master
          target_branch: staging
          title: Merge to Staging
          body: ${{ github.event.commits[0].message }}
          assignee: DerTyp7214
          label: automatic,update